### ISSUE TITLE
update for 1.20.1

### ISSUE THREAD

**Issue by vinnyg0621** [CatStorm1208/RoastedOnionsForge#16]
so I want to use this in my modpack that I upgraded from 1.19.2 to 1.20.1 but I don't see the version of the mod for 1.19.2 anymore, so could anyone maybe update this mod to 1.20(.1)?

**Comment by KatDotC** [comment]
sorry that it took so long, im working on it rn actually

**Comment by KatDotC** [comment]
I already said this on curseforge, but I will release a 1.20.1 update at some time tommorow.

**Comment by KatDotC** [comment]
I'm uploading the new update to curseforge and modrinth now

**Comment by vinnyg0621** [comment]
thank you!
